import { combineReducers } from 'redux';
import tableData from './tableReducer';
import {
    isUnflod,
    filterData,
    isShowModal,
    modalData,
    msgInfo,
    citys,
    cityList,
    isShowDetailModal,
    isCityUsing,
    currentStep,
    vehicleSelected,
    isShowAllocatOrderModal,
    isShowAllocatRouteModal,
    orderTargetKeys,
    currentAllocatVehicle,
    orderList,
    orderListJson,
    currentTargetKeys,
    vehicleRoute,
    currentVehicleRoute,
    pageLoading,
    scheduleIntro,
    currentSchedule,
    vehicles,
    isShowScheduleDetailModal,
    scheduleDetail,
    currentManualSchedule,
    user
} from './baseReducer';

export default combineReducers({
    isUnflod,
    filterData,
    isShowModal,
    modalData,
    tableData,
    msgInfo,
    citys,
    cityList,
    isShowDetailModal,
    isCityUsing,
    currentStep,
    vehicleSelected,
    isShowAllocatOrderModal,
    isShowAllocatRouteModal,
    orderTargetKeys,
    currentAllocatVehicle,
    orderList,
    orderListJson,
    currentTargetKeys,
    vehicleRoute,
    currentVehicleRoute,
    pageLoading,
    scheduleIntro,
    currentSchedule,
    vehicles,
    isShowScheduleDetailModal,
    scheduleDetail,
    currentManualSchedule,
    user
})